In [1]:
import pandas as pd

data = pd.read_csv('../all_sepsis_patient_data/demo.csv')
data

,icustay_id,hr_value_0,hr_value_1,hr_value_2,hr_value_3,hr_value_4,hr_value_5,hr_value_6,hr_value_7,hr_value_8,...,mp_value_17,mp_value_18,mp_value_19,mp_value_20,mp_value_21,mp_value_22,mp_value_23,hours_to_st,hours_to_ed,death
0,200061,1.032167,0.472796,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,...,0.800268,1.315500,0.156228,0.864672,0.413844,1.573116,0.478248,20,3,0
1,200061,0.472796,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,...,1.315500,0.156228,0.864672,0.413844,1.573116,0.478248,1.186692,21,2,0
2,200061,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,0.752481,...,0.156228,0.864672,0.413844,1.573116,0.478248,1.186692,1.122288,22,1,0
3,200061,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,0.752481,0.193110,...,0.864672,0.413844,1.573116,0.478248,1.186692,1.122288,1.251096,23,0,0
4,200075,-0.254388,-0.590011,-0.813759,-0.520089,-0.673916,-1.093445,-1.373131,-1.429068,-1.093445,...,-0.036983,-0.294599,0.156228,-0.745427,-0.681023,0.800268,0.413844,0,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,204061,0.976230,0.584670,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,...,-1.196255,0.349440,-0.487811,0.349440,-0.230195,-1.325063,0.864672,338,19,1
9996,204061,0.584670,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,...,0.349440,-0.487811,0.349440,-0.230195,-1.325063,0.864672,-1.904699,339,18,1
9997,204061,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,...,-0.487811,0.349440,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,340,17,1
9998,204061,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,0.808419,...,0.349440,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,-1.711487,341,16,1
9999,204061,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,0.808419,0.920293,...,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,-1.711487,-1.260659,342,15,1

In [3]:
ids = list(set(data['icustay_id']))
ids

[202242,
 200708,
 200711,
 200208,
 201746,
 200724,
 200729,
 203296,
 200225,
 200231,
 203815,
 202799,
 200758,
 202308,
 200773,
 202309,
 202837,
 203362,
 200191,
 203888,
 200824,
 201850,
 201857,
 203911,
 202381,
 201358,
 201360,
 203410,
 201881,
 202907,
 201372,
 200349,
 200357,
 202919,
 201401,
 202425,
 202941,
 201920,
 201924,
 203460,
 202438,
 203979,
 201422,
 203471,
 200913,
 200916,
 200917,
 202965,
 201437,
 201962,
 202476,
 200944,
 201970,
 204020,
 200439,
 200441,
 201979,
 200450,
 202499,
 200453,
 204040,
 200463,
 200977,
 202515,
 203540,
 203543,
 204061,
 200994,
 203052,
 202030,
 203055,
 203571,
 201525,
 203584,
 201027,
 201046,
 203099,
 203105,
 203111,
 202089,
 201077,
 203129,
 200061,
 201598,
 201089,
 201092,
 201605,
 202629,
 203656,
 201098,
 200075,
 201612,
 202639,
 200087,
 203674,
 202139,
 203164,
 202142,
 203679,
 203169,
 201125,
 200625,
 203186,
 203702,
 201659,
 200636,
 202684,
 200131,
 202182,
 200135,
 203212,
 200143,
 200169,
 201715,
 201215]

In [7]:
import random
random.shuffle(ids)
ids

[201089,
 202438,
 201098,
 200913,
 201979,
 201437,
 200191,
 202182,
 202499,
 201881,
 202684,
 200357,
 202308,
 200729,
 203111,
 200917,
 202965,
 201598,
 203471,
 200087,
 202139,
 200061,
 202629,
 202381,
 203105,
 202515,
 200625,
 200439,
 200916,
 203702,
 202799,
 203543,
 203674,
 200636,
 203656,
 203169,
 202425,
 200075,
 200231,
 201970,
 201027,
 201046,
 201659,
 203584,
 203186,
 203362,
 203979,
 204020,
 202242,
 202476,
 201746,
 201092,
 200944,
 200349,
 203410,
 200977,
 203571,
 203099,
 202941,
 200824,
 200708,
 201850,
 203460,
 202639,
 200758,
 202142,
 204061,
 203052,
 201605,
 200773,
 203815,
 201358,
 203540,
 202837,
 201962,
 200463,
 201401,
 202919,
 204040,
 200169,
 201372,
 200441,
 200143,
 200453,
 201612,
 200711,
 201215,
 202309,
 201125,
 201857,
 200225,
 201077,
 202907,
 201360,
 200131,
 203911,
 201525,
 203296,
 200135,
 201715,
 200994,
 201924,
 203679,
 201422,
 200208,
 202089,
 203055,
 203888,
 201920,
 200450,
 203164,
 203129,
 202030,
 203212,
 200724]

In [8]:
train_ids = ids[:100]
train_ids

[201089,
 202438,
 201098,
 200913,
 201979,
 201437,
 200191,
 202182,
 202499,
 201881,
 202684,
 200357,
 202308,
 200729,
 203111,
 200917,
 202965,
 201598,
 203471,
 200087,
 202139,
 200061,
 202629,
 202381,
 203105,
 202515,
 200625,
 200439,
 200916,
 203702,
 202799,
 203543,
 203674,
 200636,
 203656,
 203169,
 202425,
 200075,
 200231,
 201970,
 201027,
 201046,
 201659,
 203584,
 203186,
 203362,
 203979,
 204020,
 202242,
 202476,
 201746,
 201092,
 200944,
 200349,
 203410,
 200977,
 203571,
 203099,
 202941,
 200824,
 200708,
 201850,
 203460,
 202639,
 200758,
 202142,
 204061,
 203052,
 201605,
 200773,
 203815,
 201358,
 203540,
 202837,
 201962,
 200463,
 201401,
 202919,
 204040,
 200169,
 201372,
 200441,
 200143,
 200453,
 201612,
 200711,
 201215,
 202309,
 201125,
 201857,
 200225,
 201077,
 202907,
 201360,
 200131,
 203911,
 201525,
 203296,
 200135,
 201715]

In [10]:
train_X = data[data.icustay_id.isin(train_ids)]
train_X

,icustay_id,hr_value_0,hr_value_1,hr_value_2,hr_value_3,hr_value_4,hr_value_5,hr_value_6,hr_value_7,hr_value_8,...,mp_value_17,mp_value_18,mp_value_19,mp_value_20,mp_value_21,mp_value_22,mp_value_23,hours_to_st,hours_to_ed,death
0,200061,1.032167,0.472796,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,...,0.800268,1.315500,0.156228,0.864672,0.413844,1.573116,0.478248,20,3,0
1,200061,0.472796,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,...,1.315500,0.156228,0.864672,0.413844,1.573116,0.478248,1.186692,21,2,0
2,200061,0.304984,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,0.752481,...,0.156228,0.864672,0.413844,1.573116,0.478248,1.186692,1.122288,22,1,0
3,200061,-0.254388,-0.030639,0.193110,0.584670,0.304984,0.137172,0.528733,0.752481,0.193110,...,0.864672,0.413844,1.573116,0.478248,1.186692,1.122288,1.251096,23,0,0
4,200075,-0.254388,-0.590011,-0.813759,-0.520089,-0.673916,-1.093445,-1.373131,-1.429068,-1.093445,...,-0.036983,-0.294599,0.156228,-0.745427,-0.681023,0.800268,0.413844,0,25,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,204061,0.976230,0.584670,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,...,-1.196255,0.349440,-0.487811,0.349440,-0.230195,-1.325063,0.864672,338,19,1
9996,204061,0.584670,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,...,0.349440,-0.487811,0.349440,-0.230195,-1.325063,0.864672,-1.904699,339,18,1
9997,204061,0.920293,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,...,-0.487811,0.349440,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,340,17,1
9998,204061,0.920293,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,0.808419,...,0.349440,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,-1.711487,341,16,1
9999,204061,0.528733,0.528733,0.360921,0.360921,0.640607,0.528733,0.864356,0.808419,0.920293,...,-0.230195,-1.325063,0.864672,-1.904699,-1.260659,-1.711487,-1.260659,342,15,1

In [11]:
len(set(train_X.icustay_id))

100